exp_name: directsolver_toydataset
version: 0
task: DirectDisentangle

# Seed
random_seed: 42

# wandb logging config
wandb_project: disentangle
wandb_entity: ltao

training:
  # general
  batch_size: 5000
  train_loader_worker: 4
  accelerator: cpu
  devices: auto

  # optimizer
  optimizer: "AdamW"
  optimizer_cfg:
    lr: 2.0e-3
    weight_decay: 0.1

  # Logging config
  save_dir: /tmp/disentangle

  # Callbacks
  save_top_k: 2 # checkpointing
  monitor_metric: Train/epoch_avg_loss
  monitor_mode: min
  patience: 10000 # early stop

  # Misc
  limit_train_batches: 1.0
  max_epochs: 10000
  reload_after_n_epochs: 10000

  # Task specific
  compute_mmcs: True
  reg_param: 0.1

dataset:
  name: PointSphereDataset
  train_args:
    num_examples: 5000
    num_points: 256
    num_dim: 128

model:
  name: DirectSolver
  args:
    guess_factor: 8
    num_hidden: 128
    num_examples: 5000
    lamb: 0.1
    negative_penalty: 1
